import{a as w,S as q,i as d}from"./assets/vendor-550cebad.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();let y=15;async function v(){let e;i===1?e=g.elements.search.value.trim().split(" ").join("+"):e=F.trim().split(" ").join("+");const s=new URLSearchParams({key:"42996639-9210c4b9e8937070da12bf768",q:[e],image_type:"photo",orientation:"horizontal",safesearch:!0,page:[i],per_page:[y]});return(await w.get(`https://pixabay.com/api/?${s}`)).data}const f=document.querySelector(".gallery"),x=new q(".gallery a",{captionsData:"alt",captionDelay:250});function O(e){const s=e.map(({largeImageURL:r,webformatURL:a,tags:t,likes:o,views:c,comments:P,downloads:S})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${r}">
            <img class="photo" src="${a}" alt="${t}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${c}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${P}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${S}</p></li>
            </ul>
            </li>`).join("");f.insertAdjacentHTML("beforeend",s),x.refresh()}const g=document.querySelector(".search-form");let i=1,F="";const l=document.querySelector(".next-page-btn"),u=document.querySelector(".loader"),h=document.querySelector(".no-more-images");n(l);n(h);n(u);let p=1;window.onload=L;g.addEventListener("submit",$);l.addEventListener("click",E);function $(e){e.preventDefault(),f.innerHTML="";const s=e.target.elements.search.value.trim();s!==""?(i=1,F=s,b()):d.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}async function b(){try{if(n(l),n(h),m(u),i<=p){const e=await v();if(e.totalHits!=0){p=Math.ceil(e.totalHits/y),O(e.hits);const r=f.querySelector(".photos-list-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),i<p?m(l):m(h)}else d.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}}catch(e){console.log(e),d.error({message:`${e.message}`,theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{n(u),L(),g.reset()}}function E(){++i,b()}function m(e){e.classList.remove("hidden"),e.style.display="block"}function n(e){e.classList.add("hidden"),e.style.display="none"}function L(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
